// Generated by tools/sprites.py from the SNES source pack. Do not edit by hand.
window.ART = {
 "greg": {
  "src": "greg.png",
  "w": 24,
  "h": 38,
  "n": 16,
  "ax": 8,
  "ay": 34,
  "stick": [
   16,
   6
  ]
 },
 "greg_grackle": {
  "src": "greg_grackle.png",
  "w": 28,
  "h": 20,
  "n": 2,
  "ax": 15,
  "ay": 20
 },
 "cartknight": {
  "src": "cartknight.png",
  "w": 22,
  "h": 24,
  "n": 6,
  "ax": 11,
  "ay": 24
 },
 "cart": {
  "src": "cart.png",
  "w": 16,
  "h": 14,
  "n": 1,
  "ax": 7,
  "ay": 14
 },
 "ant": {
  "src": "ant.png",
  "w": 20,
  "h": 6,
  "n": 2,
  "ax": 8,
  "ay": 6
 },
 "grackle": {
  "src": "grackle.png",
  "w": 22,
  "h": 15,
  "n": 3,
  "ax": 11,
  "ay": 14
 },
 "wisp": {
  "src": "wisp.png",
  "w": 14,
  "h": 9,
  "n": 2,
  "ax": 7,
  "ay": 8
 },
 "cone": {
  "src": "cone.png",
  "w": 16,
  "h": 19,
  "n": 2,
  "ax": 8,
  "ay": 19
 },
 "grackle_prince": {
  "src": "grackle_prince.png",
  "w": 68,
  "h": 50,
  "n": 3,
  "ax": 37,
  "ay": 48
 },
 "mariachi_deep": {
  "src": "mariachi_deep.png",
  "w": 20,
  "h": 28,
  "n": 3,
  "ax": 8,
  "ay": 28
 },
 "hippo": {
  "src": "hippo.png",
  "w": 62,
  "h": 36,
  "n": 3,
  "ax": 30,
  "ay": 36
 },
 "cedar_king": {
  "src": "cedar_king.png",
  "w": 26,
  "h": 42,
  "n": 2,
  "ax": 13,
  "ay": 42
 },
 "cedar_crown": {
  "src": "cedar_crown.png",
  "w": 44,
  "h": 22,
  "n": 1,
  "ax": 22,
  "ay": 21
 },
 "cast": {
  "src": "cast.png",
  "w": 12,
  "h": 27,
  "n": 8,
  "ax": 4,
  "ay": 27
 },
 "marisa_asleep": {
  "src": "marisa_asleep.png",
  "w": 44,
  "h": 16,
  "n": 1,
  "ax": 21,
  "ay": 16
 },
 "townsfolk": {
  "src": "townsfolk.png",
  "w": 12,
  "h": 23,
  "n": 10,
  "ax": 5,
  "ay": 23
 },
 "townsfolk_props": {
  "src": "townsfolk_props.png",
  "w": 14,
  "h": 26,
  "n": 10,
  "ax": 6,
  "ay": 26
 },
 "cartknight1": {
  "src": "cartknight1.png",
  "w": 22,
  "h": 24,
  "n": 6,
  "ax": 11,
  "ay": 24
 },
 "cartknight2": {
  "src": "cartknight2.png",
  "w": 22,
  "h": 24,
  "n": 6,
  "ax": 11,
  "ay": 24
 },
 "cedar_crown_washed": {
  "src": "cedar_crown_washed.png",
  "w": 44,
  "h": 22,
  "n": 1,
  "ax": 22,
  "ay": 21
 },
 "townsfolk_b": {
  "src": "townsfolk_b.png",
  "w": 12,
  "h": 23,
  "n": 10,
  "ax": 5,
  "ay": 23
 },
 "townsfolk_c": {
  "src": "townsfolk_c.png",
  "w": 12,
  "h": 23,
  "n": 10,
  "ax": 5,
  "ay": 23
 },
 "tiles_town": {
  "src": "tiles_town.png",
  "w": 16,
  "h": 16,
  "n": 18,
  "ax": 0,
  "ay": 16
 },
 "tiles_garage": {
  "src": "tiles_garage.png",
  "w": 16,
  "h": 16,
  "n": 5,
  "ax": 0,
  "ay": 16
 },
 "tiles_riverwalk": {
  "src": "tiles_riverwalk.png",
  "w": 16,
  "h": 16,
  "n": 6,
  "ax": 0,
  "ay": 16
 },
 "tiles_zoo": {
  "src": "tiles_zoo.png",
  "w": 16,
  "h": 16,
  "n": 2,
  "ax": 0,
  "ay": 16
 },
 "tiles_school": {
  "src": "tiles_school.png",
  "w": 16,
  "h": 16,
  "n": 2,
  "ax": 0,
  "ay": 16
 },
 "tiles_alamo": {
  "src": "tiles_alamo.png",
  "w": 16,
  "h": 16,
  "n": 2,
  "ax": 0,
  "ay": 16
 },
 "tiles_culvert": {
  "src": "tiles_culvert.png",
  "w": 16,
  "h": 16,
  "n": 2,
  "ax": 0,
  "ay": 16
 },
 "tiles_greenbelt": {
  "src": "tiles_greenbelt.png",
  "w": 16,
  "h": 16,
  "n": 3,
  "ax": 0,
  "ay": 16
 },
 "tiles_city_map": {
  "src": "tiles_city_map.png",
  "w": 16,
  "h": 16,
  "n": 10,
  "ax": 0,
  "ay": 16
 },
 "map_places": {
  "src": "map_places.png",
  "w": 16,
  "h": 16,
  "n": 13,
  "ax": 0,
  "ay": 16
 },
 "bg_town": {
  "src": "bg_town.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_garage": {
  "src": "bg_garage.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_rooftop": {
  "src": "bg_rooftop.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_pearl": {
  "src": "bg_pearl.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_riverwalk": {
  "src": "bg_riverwalk.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_zoo": {
  "src": "bg_zoo.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_school": {
  "src": "bg_school.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_flood_tunnel": {
  "src": "bg_flood_tunnel.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_alamo": {
  "src": "bg_alamo.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_greenbelt": {
  "src": "bg_greenbelt.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_overpass": {
  "src": "bg_overpass.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_house": {
  "src": "bg_house.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_void": {
  "src": "bg_void.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "font": {
  "src": "font.png",
  "w": 8,
  "h": 8,
  "n": 49,
  "ax": 1,
  "ay": 1
 },
 "pickups": {
  "src": "pickups.png",
  "w": 16,
  "h": 16,
  "n": 12,
  "ax": 8,
  "ay": 16
 },
 "chest": {
  "src": "chest.png",
  "w": 16,
  "h": 12,
  "n": 2,
  "ax": 8,
  "ay": 12
 },
 "barge": {
  "src": "barge.png",
  "w": 48,
  "h": 12,
  "n": 1,
  "ax": 24,
  "ay": 12
 },
 "map_greg": {
  "src": "map_greg.png",
  "w": 12,
  "h": 12,
  "n": 4,
  "ax": 6,
  "ay": 12
 },
 "map_sedan": {
  "src": "map_sedan.png",
  "w": 12,
  "h": 10,
  "n": 2,
  "ax": 6,
  "ay": 10
 },
 "map_semi": {
  "src": "map_semi.png",
  "w": 24,
  "h": 12,
  "n": 2,
  "ax": 12,
  "ay": 12
 },
 "map_taco_truck": {
  "src": "map_taco_truck.png",
  "w": 16,
  "h": 12,
  "n": 2,
  "ax": 8,
  "ay": 12
 },
 "hud": {
  "src": "hud.png",
  "w": 8,
  "h": 8,
  "n": 7,
  "ax": 4,
  "ay": 8
 },
 "tiles_fixtures": {
  "src": "tiles_fixtures.png",
  "w": 16,
  "h": 16,
  "n": 6,
  "ax": 0,
  "ay": 16
 },
 "silverfish": {
  "src": "silverfish.png",
  "w": 48,
  "h": 24,
  "n": 3,
  "ax": 24,
  "ay": 24
 },
 "bracken_bat": {
  "src": "bracken_bat.png",
  "w": 64,
  "h": 40,
  "n": 3,
  "ax": 32,
  "ay": 40
 },
 "llorona": {
  "src": "llorona.png",
  "w": 32,
  "h": 40,
  "n": 3,
  "ax": 16,
  "ay": 38
 },
 "bat": {
  "src": "bat.png",
  "w": 16,
  "h": 16,
  "n": 2,
  "ax": 8,
  "ay": 16
 },
 "map_places_2": {
  "src": "map_places_2.png",
  "w": 16,
  "h": 16,
  "n": 3,
  "ax": 0,
  "ay": 16
 },
 "tiles_caverns": {
  "src": "tiles_caverns.png",
  "w": 16,
  "h": 16,
  "n": 6,
  "ax": 0,
  "ay": 16
 },
 "tiles_mission": {
  "src": "tiles_mission.png",
  "w": 16,
  "h": 16,
  "n": 6,
  "ax": 0,
  "ay": 16
 },
 "bg_caverns": {
  "src": "bg_caverns.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "bg_mission": {
  "src": "bg_mission.png",
  "w": 384,
  "h": 192,
  "n": 1,
  "ax": 0,
  "ay": 192
 },
 "dog": {
  "src": "dog.png",
  "w": 16,
  "h": 16,
  "n": 2,
  "ax": 8,
  "ay": 16
 },
 "cast_2": {
  "src": "cast_2.png",
  "w": 32,
  "h": 32,
  "n": 2,
  "ax": 16,
  "ay": 32
 },
 "map_places_3": {
  "src": "map_places_3.png",
  "w": 16,
  "h": 16,
  "n": 2,
  "ax": 0,
  "ay": 16
 },
 "hud_items": {
  "src": "hud_items.png",
  "w": 10,
  "h": 10,
  "n": 17,
  "ax": 5,
  "ay": 10
 }
};
